<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Bo2ZH5k' shared service.

return $this->privates['.service_locator.Bo2ZH5k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pieceVERepository' => ['privates', 'App\\Repository\\PieceVERepository', 'getPieceVERepositoryService.php', true],
], [
    'pieceVERepository' => 'App\\Repository\\PieceVERepository',
]);
