<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SOozABI' shared service.

return $this->privates['.service_locator.SOozABI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'clientFinalRepository' => ['privates', 'App\\Repository\\ClientFinalRepository', 'getClientFinalRepositoryService.php', true],
], [
    'clientFinalRepository' => 'App\\Repository\\ClientFinalRepository',
]);
