<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tQtvL2y' shared service.

return $this->privates['.service_locator.tQtvL2y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'alimentation' => ['privates', '.errored..service_locator.tQtvL2y.App\\Entity\\Alimentation', NULL, 'Cannot autowire service ".service_locator.tQtvL2y": it references class "App\\Entity\\Alimentation" but no such service exists.'],
], [
    'alimentation' => 'App\\Entity\\Alimentation',
]);
