<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._xVtGIK' shared service.

return $this->privates['.service_locator._xVtGIK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'materielBI' => ['privates', '.errored..service_locator._xVtGIK.App\\Entity\\MaterielBI', NULL, 'Cannot autowire service ".service_locator._xVtGIK": it references class "App\\Entity\\MaterielBI" but no such service exists.'],
], [
    'materielBI' => 'App\\Entity\\MaterielBI',
]);
