<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.24RaqyY' shared service.

return $this->privates['.service_locator.24RaqyY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pieceBIRepository' => ['privates', 'App\\Repository\\PieceBIRepository', 'getPieceBIRepositoryService.php', true],
], [
    'pieceBIRepository' => 'App\\Repository\\PieceBIRepository',
]);
