<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.v__H1dy' shared service.

return $this->privates['.service_locator.v__H1dy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'procesVerbal' => ['privates', '.errored..service_locator.v__H1dy.App\\Entity\\ProcesVerbal', NULL, 'Cannot autowire service ".service_locator.v__H1dy": it references class "App\\Entity\\ProcesVerbal" but no such service exists.'],
], [
    'procesVerbal' => 'App\\Entity\\ProcesVerbal',
]);
