<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VhtNLWK' shared service.

return $this->privates['.service_locator.VhtNLWK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'materielVE' => ['privates', '.errored..service_locator.VhtNLWK.App\\Entity\\MaterielVE', NULL, 'Cannot autowire service ".service_locator.VhtNLWK": it references class "App\\Entity\\MaterielVE" but no such service exists.'],
], [
    'materielVE' => 'App\\Entity\\MaterielVE',
]);
