<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.oBW5McZ' shared service.

return $this->privates['.service_locator.oBW5McZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pieceVE' => ['privates', '.errored..service_locator.oBW5McZ.App\\Entity\\PieceVE', NULL, 'Cannot autowire service ".service_locator.oBW5McZ": it references class "App\\Entity\\PieceVE" but no such service exists.'],
], [
    'pieceVE' => 'App\\Entity\\PieceVE',
]);
