<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bx0BUMF' shared service.

return $this->privates['.service_locator.bx0BUMF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'interventionRepository' => ['privates', 'App\\Repository\\InterventionRepository', 'getInterventionRepositoryService.php', true],
], [
    'interventionRepository' => 'App\\Repository\\InterventionRepository',
]);
