<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.gqJ7uMf' shared service.

return $this->privates['.service_locator.gqJ7uMf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pieceBI' => ['privates', '.errored..service_locator.gqJ7uMf.App\\Entity\\PieceBI', NULL, 'Cannot autowire service ".service_locator.gqJ7uMf": it references class "App\\Entity\\PieceBI" but no such service exists.'],
], [
    'pieceBI' => 'App\\Entity\\PieceBI',
]);
