<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..lQplIC' shared service.

return $this->privates['.service_locator..lQplIC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'materielVERepository' => ['privates', 'App\\Repository\\MaterielVERepository', 'getMaterielVERepositoryService.php', true],
], [
    'materielVERepository' => 'App\\Repository\\MaterielVERepository',
]);
