<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.i51lmZW' shared service.

return $this->privates['.service_locator.i51lmZW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'clientFinal' => ['privates', '.errored..service_locator.i51lmZW.App\\Entity\\ClientFinal', NULL, 'Cannot autowire service ".service_locator.i51lmZW": it references class "App\\Entity\\ClientFinal" but no such service exists.'],
], [
    'clientFinal' => 'App\\Entity\\ClientFinal',
]);
