<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fWa2sva' shared service.

return $this->privates['.service_locator.fWa2sva'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'procesVerbalRepository' => ['privates', 'App\\Repository\\ProcesVerbalRepository', 'getProcesVerbalRepositoryService.php', true],
], [
    'procesVerbalRepository' => 'App\\Repository\\ProcesVerbalRepository',
]);
