<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.d200LIt' shared service.

return $this->privates['.service_locator.d200LIt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'intervention' => ['privates', '.errored..service_locator.d200LIt.App\\Entity\\Intervention', NULL, 'Cannot autowire service ".service_locator.d200LIt": it references class "App\\Entity\\Intervention" but no such service exists.'],
], [
    'intervention' => 'App\\Entity\\Intervention',
]);
