<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.d200LIt.App\Entity\Intervention' shared service.

include_once $this->targetDirs[3].'\\src\\Entity\\Intervention.php';

return $this->privates['.errored..service_locator.d200LIt.App\\Entity\\Intervention'] = new \App\Entity\Intervention();
